### ISSUE TITLE
Index configuring / Filtering

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#681] opened 2019-07-24 06:52 UTC
Improve the Index support / filtering support for Open Match. Key aspects for this task are:
- What data types should we support as values for properties? 
- What filtering operations should we support for each data type?
- Dynamic index support?
- Limit the data read when processing a Pool (set of filters)

**Comment by Laremere** [comment] 2019-08-07 22:51
For purposes of discussion, this is the current API:
Indexes are configured as a specific list in the configuration.

From mmlogic.proto:
```protobuf
message QueryTicketsRequest {
  // The Pool representing the set of Filters to be queried.
  Pool pool = 1;
}

message QueryTicketsResponse {
  // The Tickets that meet the Filter criteria requested by the Pool.
  repeated Ticket tickets = 1;
}

// The MMLogic API provides utility functions for common MMF functionality such
// as retreiving Tickets from state storage.
service MmLogic {
  // QueryTickets gets the list of Tickets that match every Filter in the
  // specified Pool.
  rpc QueryTickets(QueryTicketsRequest) returns (stream QueryTicketsResponse) {
    option (google.api.http) = {
      post: "/v1/mmlogic/tickets:query"
      body: "*"
    };
  }
}

```

From messages.proto:
```protobuf
// A hard filter used to query a subset of Tickets meeting the filtering
// criteria.
message Filter {
  // Name of the ticket attribute this Filter operates on.
  string attribute = 1;

  // Maximum value. Defaults to positive infinity (any value above minv).
  double max = 2;

  // Minimum value. Defaults to 0.
  double min = 3;
}

message Pool {
  // A developer-chosen human-readable name for this Pool.
  string name = 1;

  // Set of Filters indicating the filtering criteria. Selected players must
  // match every Filter.
  repeated Filter filters = 2;
}
```

Currently only indexes are used for filtering.  Additionally, the time characteristics of querying multiple indexes isn't well described.  It looks up all indexes and does a set union of the values, not very efficient.

**Comment by Laremere** [comment] 2019-08-08 21:10
Here's an API which supports a few more filter types:

```protobuf
message Pool {
  // A developer-chosen human-readable name for this Pool.
  string name = 1;

  // Set of Filters indicating the filtering criteria. Selected players must
  // match every Filter.
  repeated RangeFilter range_filters = 2;

  repeated StringEquals string_equals = 3;

  repeated BoolEquals bool_equals = 4;
}

// Filters numerical values to only those within a range.
//   attribute: "foo"
//   max: 10
//   min: 5
// matches:
//   {"foo": 5}
//   {"foo": 7.5}
//   {"foo": 10}
// does not match:
//   {"foo": 4}
//   {"foo": 10.01}
//   {"foo": "7.5"}
//   {"foo": true}
//   {"foo": [7.5]}
//   {}
message RangeFilter {
  // Name of the ticket attribute this Filter operates on.
  string attribute = 1;

  // Maximum value.
  double max = 2;

  // Minimum value.
  double min = 3;
}

// Filters strings exactly equaling a value.
//   attribute: "foo"
//   value: "bar"
// matches:
//   {"foo": "bar"}
// does not match:
//   {"foo": "baz"}
//   {"foo": true}
//   {"foo": 5}
//   {"foo": ["bar"]}
//   {}
message StringEquals {
  string attribute = 1;

  string value = 2;
}

// Filters boolean values.
//   attribute: "foo"
//   value: true
// matches:
//   {"foo": true}
// does not match:
//   {"foo": "bar"}
//   {"foo": 1}
//   {"foo": "true"}
//   {"foo": [true]}
//   {}
message BoolEquals {
  string attribute = 1;

  bool value = 2;
}
```
# Other filter type possibilities:
## String in list:
eg if a ticket is searching for multiple game modes, could select tickets which are looking for a specific game mode. `{"modes": ["ctf","2cp","payload"]}` ; `{"attribute": "modes", "value": "ctf"}`

The issue is this can also be solved by adding flag values, eg, `{"mode-ctf": true, "mode-2cp": true, "mode-payload": true}` ; `{"attribute":"mode-ctf": "value": true}`
Overlap in capability isn't desirable.

## Distance and taxicab distance, or other types of projection:
For 2d or 3d scenarios (eg, considering skill, latency, waittime).  A reasonable query might be: 
I want everyone who has latency to Seattle <70ms, skill 100 to 150.  However, expand the skill range by 15 for every minute waiting, and the latency by 10ms for every minute waiting.  So someone with 80ms and skill 85 would show up if they wanted after a minute.  Or they could add (or combined another way) so that someone who had 80ms and 100 skill would show up after a minute, but someone with 80ms and 85 skill would only show up after waiting two minutes. (the wait time before showing up being directly summed.)

**Comment by Laremere** [comment] 2019-08-08 21:15
# Indexing

If we are able to support runtime indexing, then a possible API is:

```protobuf
message Pool {
  // A developer-chosen human-readable name for this Pool.
  string name = 1;

  Index index = 3;

  // Set of Filters indicating the filtering criteria. Selected players must
  // match every Filter.
  repeated RangeFilter range_filters = 2;

  repeated StringEquals string_equals = 4;

  repeated BoolEquals bool_equals = 5;
}


// Time complexity:
// The total time complexity of a query is O(iq + tr * f), where:
// iq = time complexity of the index query.
// tr = number of tickets returned by the index.
// ti = number of tickets in index.
// f = number of filters.

// If the index field is not set, i = 0, but all tickets are returned.

// The time complexity of updates to the indexes per ticket is O(sum(f + iu per index)), where
// f = pre-filters on the index.
// iu = time complexity of index update, if the ticket passes the filters.

message Index {
  Pool origin_pool = 1;

  oneof type {
    PoolIndex pool_index = 2;
    RangeIndex range_index = 3;
  }
}

// Holds a pre-filtered set of tickets.  Useful when every iteration of an MMF
// uses the same filter parameters.
// iq = ti
// iu = 1
message PoolIndex {}

// Allows efficient querrying along a single numerical dimension.
// Compatable Filters:
//   RangeFilter - Reduces query time to iq = log(ti)
// iu = log(ti)
message RangeIndex {
  string attribute = 1;
}
```

There are also other 2d or 3d indexes (such as a quad tree: https://en.wikipedia.org/wiki/Quadtree ) which could be supported for different query patterns.  Though I suspect that the high churn, low count characteristics of matchmaking will lend itself to simpler index types.

**Comment by Laremere** [comment] 2019-09-17 23:42
The additional filter types we wanted for 0.7 have been added.  Moving to 0.8 for other indexing work.

**Comment by Laremere** [comment] 2019-10-14 21:36
Per the proposal accepted in https://github.com/googleforgames/open-match/issues/765, OM now indexes all fields passed into search_fields, so this closes the indexing portion of this issue.

**Closed by Laremere** 2019-10-14 21:36 UTC
Labels: enhancement
