### ISSUE TITLE
replace sentinel with build in redis cluster support

### ISSUE THREAD

**Issue by dzmitry-lahoda** [googleforgames/open-match#1409] opened 2021-08-23 09:16 UTC
1. current sentinel can be replaced with cluster
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/122

2. this will allow for using kustomize to allow several redis (dev/staging) in same cluster
```
  sentinel.conf: |-
    dir "/tmp"
    bind 0.0.0.0
    port 26379
    sentinel monitor om-redis-master open-match-redis-node-0.open-match-redis-headless.open-match.svc.cluster.local 6379 2
```
3. eventually will lead to using several OMs in single cluster

4. build in better than manual, and cluster is supported by redis enterpris
5. best operator i have found is next https://github.com/OT-CONTAINER-KIT/redis-operator

**Comment by dzmitry-lahoda** [comment] 2021-08-24 14:01
it seems harder to expose redis public when it is sentinel as sentinel routs to internal master ip..

**Comment by dzmitry-lahoda** [comment] 2021-08-24 14:14
ok, made 1 replica and connected directly to master

**Comment by syntxerror** [comment] 2022-09-28 15:52
Closing this issue due to duplicate of #1377. We likely will continue supporting sentinel in our efforts to add Redis cluster support.

**Closed by syntxerror** 2022-09-28 15:52 UTC
Labels: area/feature
