### ISSUE TITLE
Creating a Player in frontendapi causes the server to spin out.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#376] opened 2019-05-08 18:05 UTC
:bug: Performing an HTTP GET to get updates on a player that does *not exist* in mm is causing a hang on the HTTP request, and this is the output from the frontendapi
```
time="2019-05-08T17:55:11Z" level=debug msg="No new results, backing off" app=openmatch component=statestorage playerId=2
time="2019-05-08T17:55:11Z" level=debug msg="state storage operation: player unmarshalled" app=openmatch cmd=HGETALL component=statestorage key=2
time="2019-05-08T17:55:11Z" level=debug msg="No new results, backing off" app=openmatch component=statestorage playerId=2
time="2019-05-08T17:55:11Z" level=debug msg="state storage operation: player unmarshalled" app=openmatch cmd=HGETALL component=statestorage key=2
time="2019-05-08T17:55:11Z" level=debug msg="No new results, backing off" app=openmatch component=statestorage playerId=2
```

**Comment by kabamllachance** [comment] 2019-05-08 18:07
It’s not backing off, it looks like it’s caught in a loop.  Also I would expect just a 404 response in this case.

**Comment by kabamllachance** [comment] 2019-05-08 18:08
EX: GET http://localhost:51504/v1/frontend/players/2
Where player id 2 has never had a createPlayer request and does not yet exist in redis

**Comment by jeremyje** [comment] 2019-05-13 21:54
@sawagh can you look into this?

**Comment by kabamllachance** [comment] 2019-05-13 22:04
I may have been mistaken on the expected behaviour of this GET request.  Please first check that it is as intended! :)

**Comment by sawagh** [comment] 2019-05-13 23:34
I would expect the behavior to be 404 - so the bug is valid :) 

The current code fetches the the Player from redis and checks for any changes from what it has last seen in response to the update method. The HGETALL used to fetch the non existent player returns an empty list of properties - and that constructs an empty player each time :) so the check never fails but simply keeps spinning noticing no changes from the last 'Empty' Player.

Will keep this bug active and add a test case in 0.6 to validate a 404 there. I am not leaning toward hot-fixing for 0.5 unless this blocks something.

**Comment by kabamllachance** [comment] 2019-05-13 23:55
That is ok for me, thank you @sawagh !

**Comment by sawagh** [comment] 2019-06-06 18:28
Yufan has added a test for this in v0.6! Closing issue.

**Closed by sawagh** 2019-06-06 18:28 UTC
