### ISSUE TITLE
Default Helm chart shouldn't deploy with test components

### ISSUE THREAD

**Issue by HazWard** [googleforgames/open-match#1198] opened 2020-04-24 17:17 UTC
**Is your feature request related to a problem? Please describe.**
When deploying Open Match to integration environments for development iterations, some of the test components are also deployed (the Kubernetes resources in the [`templates/tests` directory](https://github.com/googleforgames/open-match/tree/master/install/helm/open-match/templates/tests). These resources are useful when doing the initial evaluation of Open Match but once you are ready to use it in scenarios close to production they become unnecessary.

**Describe the solution you'd like**
Similarly to how the `open-match-scale`, `open-match-core` and `open-match-telemetry` can be toggled on and off using Helm values (`enabled` set to true), an additional `open-match-test.enabled` variable would be ideal in making sure Open Match is deployed only with the components the developer needs.

**Describe alternatives you've considered**
I've used the Helm's template command to generate a rendered chart and simply removed the test components manually as I also tailor the configuration to my workloads but this step can be error-prone a bit error-prone.

**Comment by yfei1** [comment] 2020-04-25 06:46
Looks like a duplicate of #1141. In helm3 test is not installed by default via `helm install` and can be explicitly disabled by `helm template --no--hooks`,

**Comment by HazWard** [comment] 2020-04-28 22:23
I'm using `--no-hooks` (in Helm 3.2.0) and it doesn't seem to work, the test components are still present.

The command I used is: `helm template --no-hooks my-release --namespace open-match open-match/open-match`

**Closed** 2020-05-11 19:16 UTC
