### ISSUE TITLE
Failure to connect to Redis after upgrading from 0.9 to 0.10 with Istio

### ISSUE THREAD

**Issue by Evertras** [googleforgames/open-match#1183] opened 2020-04-02 03:44 UTC
**What happened**:

In our GKE cluster, we are using Istio.  We installed Istio with the following command:

```bash
istioctl manifest apply --set profile=demo \
                                  --set values.gateways.istio-ingressgateway.sds.enabled=true \
                                  --set values.global.k8sIngress.enabled=true \
                                  --set values.global.k8sIngress.enableHttps=true \
                                  --set values.global.k8sIngress.gatewayName=ingressgateway
```

We ran Open Match 0.9 with this configuration without any issues.  We installed Open Match 0.9 with YAML.  We made one change to the base YAML in `01-open-match-core.yaml` by adding `istio-injection: enabled` in order to use the Envoy proxies and hook everything up into our Istio mesh:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: open-match
  labels:
    app: open-match
    release: open-match
    istio-injection: enabled
```

We also added an Istio Virtual Service for the front end:

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: om-frontend
spec:
  hosts:
    - "om-frontend"
  http:
    - match:
      - port: 50504
      route:
        - destination:
            host: om-frontend
```

*That part isn't necessary, but I'm listing it here for completeness sake as we were starting to add more virtual services for more control via Istio; removing it had no effect on the outcome*

We additionally installed the default evaluator using `06-open-match-override-configmap.yaml` and `07-open-match-default-evaluator.yaml` without any modifications.

This worked fine, and we were able to use the demo and now our own matchmaking components with Open Match.

After 0.10 was released, we deleted 0.9 from our cluster.  We replaced all the YAML with the updated 0.10 versions, and added the `istio-injection: enabled` label to the namespace as before.  After installing the core YAML, the virtual service, and the default evaluator, Open Match was up and running again.

The problem comes when we try to create a ticket.  Following the error we found the following logs in the Open Match Frontend:

```
time="2020-04-02T02:13:41Z" level=debug msg="Attempting to connect to Redis Sentinel" app=openmatch component=statestore.redis sentinelAddr="om-redis.open-match.svc.cluster.local:26379"
time="2020-04-02T02:13:41Z" level=error msg="failed to set the value for ticket" app=openmatch cmd=SET component=statestore.redis error="READONLY You can't write against a read only replica." key=bq2kklcppmal23kiefjg
time="2020-04-02T02:13:41Z" level=error msg="failed to create the ticket" app=openmatch component=app.frontend error="rpc error: code = Internal desc = READONLY You can't write against a read only replica." ticket="id:\"bq2kklcppmal23kiefjg\" search_fields:<string_args:<key:\"version\" value:\"game\" > > extensions:<key:\"group\" value:<type_url:\"type.googleapis.com/matchmaking.tickets.Group\" value:\"\\022\\014\\n\\nfakeplayer\\032\\nfakeplayer\" > > create_time:<seconds:1585793621 nanos:765438314 > "
```

We also see the following errors in Open Match Query being triggered when our Director asks for matches:

```
time="2020-04-02T03:42:38Z" level=debug msg="Attempting to connect to Redis Sentinel" app=openmatch component=statestore.redis sentinelAddr="om-redis.open-match.svc.cluster.local:26379"
time="2020-04-02T03:42:38Z" level=error msg="failed to connect to redis" app=openmatch component=statestore.redis error="dial tcp 127.0.0.1:6379: connect: connection refused"
time="2020-04-02T03:42:38Z" level=error msg="Failed to run request." app=openmatch component=app.query error="rpc error: code = Unavailable desc = dial tcp 127.0.0.1:6379: connect: connection refused"
```

I suspect the problem is with the addition of Redis Sentinel, as that seems to be the only major change from 0.9's deployment.  Unfortunately I have no experience with Sentinel, so I'm at a loss as to what to check or change from here.

**What you expected to happen**:

When creating a ticket via the Open Match Frontend, the connection to Redis is properly made and the ticket is created.

**How to reproduce it (as minimally and precisely as possible)**:

[Install Istio](https://istio.io/docs/setup/install/istioctl/):

```
istioctl manifest apply --profile=demo
```

Add `istio-injection: enabled` to the Open Match namespace labels in YAML.

Install Open Match via YAML, including the default evaluator (06/07).

Attempt to create ticket.

Observe front end logs.

**Anything else we need to know?**:

Istioctl version:

```
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (30 proxies)
```

**Output of `kubectl version`**:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: GKE

**Open Match Release Version**: 0.10

**Install Method(yaml/helm):**: YAML

**Comment by Evertras** [comment] 2020-04-02 05:32
After more searching and experimenting, I found https://github.com/istio/istio/issues/7495 which is closed but people are still apparently running into issues.

I removed `clusterIP: None` from all the Open Match k8s Service entries except Redis.  I then removed Istio sidecar injection from all Redis pods, which took it out of the mesh.  This got me much closer, but still errors:

```
time="2020-04-02T05:24:02Z" level=debug msg="Attempting to connect to Redis Sentinel" app=openmatch component=statestore.redis sentinelAddr="om-redis.open-match.svc.cluster.local:26379"
time="2020-04-02T05:24:03Z" level=error msg="failed to set the value for ticket" app=openmatch cmd=SET component=statestore.redis error="read tcp 10.31.2.119:50340->10.31.2.121:6379: read: connection reset by peer" key=bq2ndsmke2tuph7g0o3g
```

A quick check on pod IPs indicates that `10.31.2.121:6379` is the Redis master pod.

This brings up a side question: why is `clusterIP: None` set on Open Match services?  Removing this line significantly improved Istio's visibility on the services and explains general connectivity oddness I'd been seeing earlier.

This issue is almost certainly an Istio one and not an Open Match one at this point, but I'll record any other info I find here in case someone else stumbles on the same problem.

**Comment by Evertras** [comment] 2020-04-02 06:01
I was able to get things working again by removing Istio sidecar injection entirely.  However, I still need to modify the services to remove `clusterIP: None` from the Open Match frontend/backend/query services in order to connect to them with my services.  My original attempts at removing the sidecar injection are broken and repeatable; if I try to do the basic YAML install, I can't connect to the services properly from within Istio land, which is probably related to the issue linked above.

So after all that, it's really just the question: What am I breaking by removing `clusterIP: None` from the services?

**Comment by yfei1** [comment] 2020-04-02 18:16
Hey @Evertras,

Thanks for bringing up this issue. One thing that I'm not sure of is Open Match has the headless service `clusterIP: None` change checked in since v0.8. If you were able to integrate OM with Istio in v0.9, then the transition from 0.9 to 0.10 should be quite smooth, so my gut tells me headless service itself is not the root cause of the issue.

As for the sentinel feature that was checked-in in v0.10, there is a way to turn it off via helm by setting `--set redis.sentinel.enabled=false`. Could you possibly turn it off and see if Open Match could work as expected with Istio?

I don't have that much experience with Istio, but I did try to integrate Open Match with Envoy in v0.10 and was able to get it to work without the sentinel component.

The `clusterIP: None` option set on Open Match v0.8 is a workaround to integrate gRPC services in Kubernetes environment - in short, gRPC is HTTP2 based and use long-live connections, so the Virtual IP services in Kubernetes are not able to load balance them correctly. Under a high load scenario, I was able to see 99% of the traffic go into one pod, which makes Open Match unable to scale horizontally. Issue #1128 has more context about this change.

**Comment by Evertras** [comment] 2020-04-03 02:28
Yeah, I saw that this was also the case in 0.9.  I was seeing some odd connection issues sporadically, and I think that was the culprit.  Adding sentinel may have been the tipping point for Istio to throw up its hands and stop working.  I'll try a Helm install w/out sentinel this weekend when I have some more time to see if that's true.  If you were able to get things working with Envoy then I'm optimistic that it will work with Istio.

One of the big reasons we're using Istio is actually to solve the exact problem you're describing with load balancing to gRPC endpoints.  We were also hitting that issue with our internal services.  So if that's the reason it's set to `None`, I think we'll try removing that and then ensuring that Istio is actually load balancing properly after a horizontal scale trigger.  If it works we'll go with that for now.

**Comment by Evertras** [comment] 2020-04-03 03:34
To clarify the 'odd connection issues', the problem was that if the underlying Open Match pods changed then my client wouldn't disconnect (because Envoy is handling the connection), but because it's a headless service then Istio wasn't making Envoy aware of the new underlying pods that were coming up.  So at that point there was a connection from my service its Envoy, but Envoy didn't know where to point requests so they kept timing out.  I had no idea what was causing this behavior until now.

**Comment by yfei1** [comment] 2020-04-04 03:08
Wanna share some notes about my past experiments with Envoy

> If you were able to get things working with Envoy then I'm optimistic that it will work with Istio.

Just a heads-up, I was able to get Open Match to work with Envoy but I haven't done any stress tests against this integration yet so the actual performance might be worse than the benchmark numbers that we get in v.10 release note, a prototype of this integration is available at https://github.com/yfei1/open-match/commit/0039fa7b00cc99f134294950cd74d7a4b46d4fb6.

> One of the big reasons we're using Istio is actually to solve the exact problem you're describing with load balancing to gRPC endpoints. We were also hitting that issue with our internal services. 

I see you are using Istio to solve the load balancing problem, does your open match clients live in the same cluster as open match services? If that's the case, disable Istio injection for Open Match components may also work. 

> So if that's the reason it's set to `None`, I think we'll try removing that and then ensuring that Istio is actually load balancing properly after a horizontal scale trigger. If it works we'll go with that for now.

I'm not quite sure if removing the `clusterIP: None` option can lead to the same behavior since #864 also changed some internal grpc setups such that the headless service could work. You may want to revert this change in your fork if you go down with the Istio path :(

> To clarify the 'odd connection issues', the problem was that if the underlying Open Match pods changed then my client wouldn't disconnect (because Envoy is handling the connection), but because it's a headless service then Istio wasn't making Envoy aware of the new underlying pods that were coming up.

Have you tried adding [gRPC's keepalive checks](https://open-match.dev/site/docs/guides/best_practices/#setup-grpc-keepaliveenforcementpolicy-for-your-mmf-and-evaluator-server) to your clients?

**Comment by syntxerror** [comment] 2022-08-02 14:55
Closing this issue due to staleness. @Evertras please reopen if this was not resolved on your end.

**Closed by syntxerror** 2022-08-02 14:55 UTC
Labels: kind/bug, area/productionization
