### ISSUE TITLE
Documentation: Offload reads to Redis replicas

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#1125] opened 2020-02-19 00:34 UTC
Add a production guideline section and point out it is possible to offload reads to Redis replicas if someone need more scalability than the vanilla Open Match.
 

See #1118  for the details

**Comment by syntxerror** [comment] 2022-09-28 15:55
Closing due to duplicate of #1388. Documentation will be added to support this issue

**Closed by syntxerror** 2022-09-28 15:55 UTC
Labels: area/docs, area/productionization
