### ISSUE TITLE
make presubmit shouldn't update random files

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1132] opened 2020-02-25 22:17 UTC
Running make presubmit just updated third_party/google/api/backend.proto

I think we should have a process that ensures these files are up to date, however it means that any changes end up getting added to random irrelevant prs.

**Comment by yfei1** [comment] 2020-02-26 02:51
duplicate of #491?

**Comment by Laremere** [comment] 2020-02-28 02:57
No, that one is that it's possible to change the source files without the effected files changed (eg, change proto without the go generated files updating.)

This is that it seems that this file will randomly update in unrelated prs.  I think the source isn't version pinned?

**Closed** 2020-04-03 19:01 UTC
