### ISSUE TITLE
Provide an API to show how many tickets are waiting for match 

### ISSUE THREAD

**Issue by lihaif** [googleforgames/open-match#1312] opened 2020-12-16 22:12 UTC
**Is your feature request related to a problem? Please describe.**

We want to dynamically change the logic to partition tickets based on the number of tickets in Redis waiting for match. e.g. No partition is needed when the number of tickets is less than 3000. Start to partition tickets when the number of tickets is more than 3000.

There are APIs in Query Service to get Ticket IDs and Tickets, but I suspect the tickets returned should be no more than the value of `queryPageSize `.  And we do not need that much information for performance reason, we just need an integer to show how many tickets in Redis that match the filters.

**Describe the solution you'd like**

A new API be provided in Query Service to return the number of tickets that matches the filters. When there is no filter provided, it should return the total number of tickets in Redis.

**Describe alternatives you've considered**

**Additional context**

**Comment by syntxerror** [comment] 2022-03-22 18:16
Duplicate of #683

**Closed by syntxerror** 2022-03-22 18:16 UTC
Labels: area/feature
